#pragma once

#define ANALOG_JOYSTICK_X_AXIS_PIN GP26  
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP27  
#define ANALOG_JOYSTICK_AXIS_MIN 100
#define ANALOG_JOYSTICK_AXIS_MAX 1023
// #define ANALOG_JOYSTICK_CLICK_PIN GP22
#define ANALOG_JOYSTICK_CUTOFF true
#define POINTING_DEVICE_INVERT_Y
#define POINTING_DEVICE_INVERT_X
#define ANALOG_JOYSTICK_SPEED_REGULATOR 10