#pragma once

#define ANALOG_JOYSTICK_X_AXIS_PIN GP26  
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP27  
#define ANALOG_JOYSTICK_AXIS_MIN 50
// #define ANALOG_JOYSTICK_AXIS_MAX 1023
// #define ANALOG_JOYSTICK_CLICK_PIN GP22